version: 2.1
executors:
  docker-executor:
    docker:
      - image: circleci/python:3.7

jobs:
  build_and_push:
    executor: docker-executor
    steps:
      - setup_remote_docker:
          version: 20.10.7
          docker_layer_caching: true
      - checkout
      - run:
          name: Install AWS CLI
          command: |
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
      - run:
          name: Build and push Docker image
          command: |
            aws ecr get-login-password --region ${AWS_REGION}| docker login --username AWS --password-stdin 691592260817.dkr.ecr.us-west-2.amazonaws.com
            docker build -t ${ECR_REPOSITORY}:main .
            docker tag ${ECR_REPOSITORY}:main ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPOSITORY}:main
            docker push ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPOSITORY}:main
workflows:
  version: 2
  build-deploy:
    jobs:
      - build_and_push
